### ISSUE TITLE
Is it possible to build a AST with this method

### ISSUE THREAD

**Issue by khrome83** [yelouafi/pcomb#3]
I am really curious about your design. 

I am having a hard time wrapping my head around some aspects of it. But I was curious about your thoughts of using an approach like this to build AST output.

I see a lot of JSON to AST parsers for example, and they don't do anything as nifty. 

If this is not the right direction, can you point me in a better direction?

**Comment by yelouafi** [comment]
see https://github.com/yelouafi/create-a-simple-functional-language for examples. Basically you use `token` to parser basic lexemes and  `.map` or `.apply` to transform the parsed strings into more structured output

Note this is not an industrial strength parser, it's more a thing for language amateurs. If you want something suited for production you may take a look at https://github.com/jneen/parsimmon

**Comment by khrome83** [comment]
TYVM
